name: NPM-CREATE
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Welcome to sukresh repo

      # Runs a set of commands using the runners shell
      - name: Update data to repo
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.USERNAME}}
          git add .
          git status
          git commit -m "adding npm files"
          git push origin main
